export const dynamic = 'force-dynamic'; // defaults to auto

export async function GET(request: Request) {
  const projects = [
    {
      id: "paddle",
      slug: "paddle",
      body: "Global payments infrastructure for SaaS and digital products.",
      collection: "posts",
      data: {
        layout: "default",
        pubDate: new Date().toISOString(),
        title: "Paddle",
        description: "Global payments infrastructure for SaaS and digital products.",
        category: "projects",
        image: "/images/paddle.svg",
        tags: ["Payments", "SaaS", "Billing"],
        projectURL: "https://www.paddle.com",
        repoURL: null,
      },
    },
    {
      id: "linguaexams",
      slug: "linguaexams",
      body: "Language exam preparation platform with structured practice and assessments.",
      collection: "posts",
      data: {
        layout: "default",
        pubDate: new Date().toISOString(),
        title: "LinguaExams",
        description: "Language exam preparation platform with structured practice and assessments.",
        category: "projects",
        image: "/images/linguaexams.png",
        tags: ["EdTech", "Assessments", "Learning"],
        projectURL: "https://linguaexams.com",
        repoURL: null,
      },
    },
    {
      id: "metrade",
      slug: "metrade",
      body: "Trading analytics and market insights for smarter decisions.",
      collection: "posts",
      data: {
        layout: "default",
        pubDate: new Date().toISOString(),
        title: "Metrade",
        description: "Trading analytics and market insights for smarter decisions.",
        category: "projects",
        image: "/images/metrade.png",
        tags: ["Fintech", "Analytics", "Trading"],
        projectURL: "https://metrade.io/",
        repoURL: null,
      },
    },
    {
      id: "igeoerp",
      slug: "igeoerp",
      body: "Field service ERP for pest control and HVAC companies, with scheduling, CRM, and AI-optimized routing.",
      collection: "posts",
      data: {
        layout: "default",
        pubDate: new Date().toISOString(),
        title: "iGEO ERP",
        description: "Field service ERP for pest control and HVAC companies, with scheduling, CRM, and AI-optimized routing.",
        category: "projects",
        image: "/images/igeoerp.png",
        tags: ["ERP", "Field Service", "CRM"],
        projectURL: "https://igeoerp.com/en/",
        repoURL: null,
      },
    },
    {
      id: "yoti",
      slug: "yoti",
      body: "Digital identity and age verification platform, processing millions of verification checks monthly.",
      collection: "posts",
      data: {
        layout: "default",
        pubDate: new Date().toISOString(),
        title: "Yoti",
        description: "Digital identity and age verification platform, processing millions of verification checks monthly.",
        category: "projects",
        image: "/images/yoti.png",
        tags: ["Identity", "Verification", "Security"],
        projectURL: "https://www.yoti.com/",
        repoURL: null,
      },
    },
    {
      id: "amadeus",
      slug: "amadeus",
      body: "Global travel technology platform serving airlines, airports, hotels, and travel agencies worldwide.",
      collection: "posts",
      data: {
        layout: "default",
        pubDate: new Date().toISOString(),
        title: "Amadeus",
        description: "Global travel technology platform serving airlines, airports, hotels, and travel agencies worldwide.",
        category: "projects",
        image: "/images/amadeus.png",
        tags: ["Travel", "Enterprise", "APIs"],
        projectURL: "https://amadeus.com/en",
        repoURL: null,
      },
    },
    {
      id: "emr",
      slug: "emr",
      body: "Swiss registry certifying and connecting patients with qualified complementary medicine practitioners.",
      collection: "posts",
      data: {
        layout: "default",
        pubDate: new Date().toISOString(),
        title: "EMR",
        description: "Swiss registry certifying and connecting patients with qualified complementary medicine practitioners.",
        category: "projects",
        image: "/images/emr.svg",
        tags: ["Healthcare", "Directory", "Switzerland"],
        projectURL: "https://emr.ch/",
        repoURL: null,
        iconOnLight: true,
      },
    },
    {
      id: "deepimpact",
      slug: "deepimpact",
      body: "Swiss AI and software consultancy building custom LLM-powered solutions for banking, insurance, and industry clients.",
      collection: "posts",
      data: {
        layout: "default",
        pubDate: new Date().toISOString(),
        title: "Deep Impact AG",
        description: "Swiss AI and software consultancy building custom LLM-powered solutions for banking, insurance, and industry clients.",
        category: "projects",
        image: "/images/deepimpact.png",
        tags: ["AI", "Consultancy", "Switzerland"],
        projectURL: "https://deepimpact.ch",
        repoURL: null,
      },
    },
    {
      id: "aireuropa",
      slug: "aireuropa",
      body: "Spanish airline operating domestic and international flights, supported by back-office management tools.",
      collection: "posts",
      data: {
        layout: "default",
        pubDate: new Date().toISOString(),
        title: "Air Europa",
        description: "Spanish airline operating domestic and international flights, supported by back-office management tools.",
        category: "projects",
        image: "/images/aireuropa.jpg",
        tags: ["Airline", "Travel", "Enterprise"],
        projectURL: "https://www.aireuropa.com",
        repoURL: null,
      },
    },
    {
      id: "halconviajes",
      slug: "halconviajes",
      body: "Spanish online travel agency offering vacation packages, cruises, hotels, and flights across 450+ locations.",
      collection: "posts",
      data: {
        layout: "default",
        pubDate: new Date().toISOString(),
        title: "Halcón Viajes",
        description: "Spanish online travel agency offering vacation packages, cruises, hotels, and flights across 450+ locations.",
        category: "projects",
        image: "/images/halconviajes.svg",
        tags: ["Travel", "E-commerce", "Tourism"],
        projectURL: "https://www.halconviajes.com",
        repoURL: null,
        iconOnLight: true,
      },
    },
    {
      id: "trenitalia",
      slug: "trenitalia",
      body: "Italian national railway operator, with management tools for domestic, regional, and high-speed rail services.",
      collection: "posts",
      data: {
        layout: "default",
        pubDate: new Date().toISOString(),
        title: "Trenitalia",
        description: "Italian national railway operator, with management tools for domestic, regional, and high-speed rail services.",
        category: "projects",
        image: "/images/trenitalia.svg",
        tags: ["Transportation", "Rail", "Enterprise"],
        projectURL: "https://www.trenitalia.com",
        repoURL: null,
      },
    },
    {
      id: "touchnote",
      slug: "touchnote",
      body: "Platform for creating and sending personalized physical postcards and greeting cards, delivered globally.",
      collection: "posts",
      data: {
        layout: "default",
        pubDate: new Date().toISOString(),
        title: "TouchNote",
        description: "Platform for creating and sending personalized physical postcards and greeting cards, delivered globally.",
        category: "projects",
        image: "/images/touchnote.png",
        tags: ["E-commerce", "Print", "Platform"],
        projectURL: "https://touchnote.com/",
        repoURL: null,
        iconOnLight: true,
      },
    },
  ];

  return new Response(JSON.stringify({ postsData: projects }), { status: 200 });
}
